name: fstore
publish_to: "none"
description: LOLL

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.8.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  inspireui:
    path: ./modules/common_library

  # Base
  pedantic: 1.11.0
  intl: 0.17.0
  crypto: 3.0.1
  path_provider: 2.0.1
  url_launcher: 6.0.2
  app_tracking_transparency: 2.0.1
  localstorage: 4.0.0+1
  http: 0.13.3
  http_auth: 1.0.0
  uni_links2: 0.6.0+2
  share: 2.0.1

  # FIREBASE PACKAGES
  firebase_core: 1.2.0
  firebase_analytics: 8.1.0
  firebase_auth: 1.2.0
  cloud_firestore: 1.0.7
  firebase_remote_config: 0.10.0
  firebase_dynamic_links: 2.0.4
  firestore_ui: 1.20.0

  # STATE MANAGEMENT
  provider: 5.0.0
  get_it: 7.1.3
  event_bus: 2.0.0

  # SPLASH SCREEN, ONBOARD
  flare_splash_screen: 4.0.0
  rive: 0.7.10
  liquid_swipe: 2.1.0

  # ICON FONTS
  font_awesome_flutter: 9.0.0
  cupertino_icons: 1.0.3

  # WEB TOOLS
  html_unescape: 2.0.0
#  webview_flutter: 2.0.7
  webview_flutter: 2.0.4
  flutter_widget_from_html: 0.6.1
  flutter_webview_plugin:
    git:
      url: https://github.com/fonibo/flutter_webview_plugin.git
  responsive_builder: 0.4.1

  # MAP
  google_maps_flutter: 2.0.5
  location: 4.1.1

  # AUTHENTICATION
  the_apple_sign_in: 1.1.1
#  flutter_facebook_auth: 3.4.0
  flutter_facebook_auth: ^3.5.1
  google_sign_in: 5.0.3
  sms_autofill: 2.0.0

  # PUSH NOTIFICATION
  firebase_messaging: 10.0.0
  notification_permissions: 0.5.0
  onesignal_flutter: 3.2.4

  # PAYMENTS
  awesome_card: 1.1.5
  stripe_sdk: 5.0.0-nullsafety.0
  razorpay_flutter:
    git:
      url: https://github.com/inspireui/razorpay-flutter.git
      ref: null_safety

  # FILES, IMAGES
  file_picker: 3.0.1
  cached_network_image: 3.0.0
  image: 3.0.2
  transparent_image: 2.0.0
  extended_image: 4.1.0
  image_picker: 0.7.5+2
  flutter_native_image: 0.0.6
  multi_image_picker2: 5.0.0

  # VIDEOS
  percent_indicator: 3.0.1
  video_player: 2.1.1

  # ADS
  google_mobile_ads: 0.13.0
  facebook_audience_network:
    git:
      url: https://github.com/RR-Reddy/facebook_audience_network.git
      ref: null-safety

  # TOOLS
  google_fonts: 2.1.0
  random_string: 2.2.0-nullsafety
  json_annotation: 4.0.1
  timeago: 3.0.2
  universal_platform: 1.0.0-nullsafety
  uuid: 3.0.4
  vector_math: 2.1.0
#  async: 2.6.1
  async:
  easy_debounce: 2.0.0
  devicelocale: 0.4.1
  collection: 1.15.0
  visibility_detector: 0.2.0
  rate_my_app: 1.1.0+1
  package_info: 2.0.0

  # UI
  auto_size_text: 3.0.0-nullsafety.0
  flutter_spinkit: 5.0.0
  page_indicator: 0.4.1
  smooth_page_indicator: 0.3.0-nullsafety.0
  animated_text_kit: 4.2.1
  animations: 2.0.0
  flash: 1.5.2+1
  flutter_staggered_grid_view: 0.4.0
  flutter_statusbarcolor_ns: 0.3.0-nullsafety
  flutter_swiper_null_safety: 1.0.2
  pull_to_refresh: 2.0.0
  implicitly_animated_reorderable_list: 0.4.0
  rubber: 1.0.0
  pin_code_fields: 7.1.0
  country_code_picker: 2.0.1
  country_pickers: 2.0.0

  #### For Listing App
  carousel_slider: 4.0.0-nullsafety.0

  #### For Shopify GraphQL
  graphql: 5.0.0-nullsafety.4

  #### For Booking feature
  dropdown_search: 0.6.1
  flutter_calendar_carousel: 2.0.1
  animate_icons: ^2.0.0

  # My
  basic_utils: 3.4.0
  page_transition: ^2.0.4
  flutter_credit_card: ^3.0.0
  credit_card_validator: ^2.0.0
  credit_card_validate: ^0.0.3
  translator: ^0.1.7


dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
    version: any
  flutter_localizations:
    sdk: flutter
  test: ^1.16.5
  flutter_launcher_icons: ^0.9.0
  flutter_app_name:

flutter_app_name:
  name: "Spider3D"


## Enable To run json serializer, run:
## flutter pub run build_runner build --build-filter="lib/models/serializers/*.dart" --delete-conflicting-outputs
## flutter pub run build_runner serve --build-filter="lib/models/serializers/*.dart"
#  build_runner: 2.0.3
#  json_serializable: 4.1.2


# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/config/
    - lib/config/mocks/
    - lib/config/states/
    - lib/config/stories/
    - assets/icons/credit_cards/
    - assets/icons/tabs/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - google_fonts/
  fonts:
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
